### ISSUE TITLE
f581d2779680eb6ba734282cb9940ab096810455

### ISSUE THREAD

**Issue by jasti99** [NucleoidJS/Nucleoid#45]

**Comment by canmingir** [comment]
🤔?

**Comment by jasti99** [comment]
![Screenshot_20221013_125636~2](https://user-images.githubusercontent.com/117423555/217538196-3a4be394-98ab-4bc5-a400-ccf0255793a3.jpg)

**Comment by jasti99** [comment]
[Username](url)
